// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace HanTing
{

    public class Cheapest
    {

        public string Name;

        public string ActivityID;

        public bool IsOverBooked;

        public string RoomType;

        public string HotelID;

        public string MemberLevel;

        public string ActivityUrl;

        public string ActivityBeginTime;

        public string ActivityEndTime;

        public string ConditionInt;

        public string AdvanceHousingInt;

        public int ConditionType;

        public string[] SupportMemberLevel;

        public object Description;

        public string IconUrl;

        public string Price;

        public int BreakfastCount;

        public bool IsSetPromotion;

        public bool IsBlocked;

        public string MarketPrice;

        public bool ShowResv;

        public bool LessThan;

        public int MinStockCount;

        public object DailyRoomStock;

        public bool IsMustOnlinePay;

        public bool IsBindMemberPrice;
    }

}
