// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace HanTing
{
    public class Data
    {
        public HotelList[] HotelList;

        public object CityList;

        public int HKCount;

        public int HTCount;

        public int HZCount;

        public int XCCount;

        public int XYCount;

        public int MXCount;

        public int TotalCout;
    }

}
