// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace HanTing
{

    public class HanTingData
    {

        public int ResultType;

        public object Message;

        public object MoreInfo;

        public Data Data;

        public object ErrorKey;
    }

}
