// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace HanTing
{

    public class HotelImage
    {

        public int ImageID;

        public int ImageTypeID;

        public string ImageName;

        public string HotelID;

        public string ImageDesc;

        public string ImageUrl;

        public string RoomTypeID;

        public int? FacilityType;
    }

}
