// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace HanTing
{

    public class HotelList
    {
        public Info Info;

        public int Distance;

        public Room[] Rooms;

        public string Navigate360;
    }

}
