// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace HanTing
{

    public class HotelPhoto
    {

        public int ID;

        public string HotelID;

        public string ImagePath;

        public bool InUse;

        public string RoomTypeID;

        public string Description;
    }

}
