// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace HanTing
{

    public class HotelNotice
    {

        public int ID;

        public string HotelID;

        public string BeginTime;

        public string EndTime;

        public string Description;

        public bool InUse;

        public bool IsAboutResv;
    }

}
