// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
namespace HanTing
{

    public class HotelSupportCreditCard
    {

        public string HotelID;

        public int CardID;

        public string CardName;

        public string ImagePath;
    }

}
