// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace HanTing
{

    public class HotelRoute
    {

        public int ID;

        public string HotelID;

        public int RouteID;

        public string RouteFrom;

        public string Description;

        public bool IsBus;

        public bool IsMetro;

        public bool IsDrive;

        public bool? IsTaxi;

        public bool? IsWalk;
    }

}
