// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace HanTing
{

    public class HotelFacility
    {

        public int FacilityID;

        public string Name;

        public string Descript;

        public int SortValue;

        public int FacilityTypeID;

        public string FacilityTypeName;
    }

}
