// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
namespace HanTing
{

    public class Info
    {

        public string CityName;

        public double? HotelLowestPrice;

        public HotelNotice[] HotelNotice { get; set; }

        public HotelFacility[] HotelFacility;

        public HotelPhoto[] HotelPhoto;

        public HotelSupportCreditCard[] HotelSupportCreditCard;

        public HotelImage[] HotelImage;

        public HotelRoute[] HotelRoute;

        public object[] HotelPromotion;

        public string ID;

        public string HotelName;

        public string HotelNameEn;

        public int HotelStyle;

        public string Nation;

        public string Zip;

        public string Telephone;

        public string Fax;

        public string Address;

        public string Descript;

        public int CityID;

        public int RoomCount;

        public int HotelType;

        public bool IsOpening;

        public string BusinessDate;

        public bool IsShowPrepare;

        public double CommentScore;

        public int CommentCount;

        public string HeaderPhoto;

        public object HallIDs;

        public double Lng;

        public double Lat;

        public bool IsOnlyChinese;

        public bool IsSupportValueCardPay;

        public bool IsSupport360View;

        public bool IsOpenResv;

        public bool IsOpenOnlineCheckIn;

        public bool IsUsualHotel;

        public bool IsOverBooked;

        public bool IsExchangePointPromo;

        public int ExchangePointDiscountValue;
    }

}
