// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace HanTing
{

    public class Info2
    {
        public string BedType;

        public string BedTypeShort;

        public string BedSize;

        public string RoomArea;

        public string Floor;

        public string Window;

        public string NoSmokingFloor;

        public string SupportNetwork;

        public string MaxCheckInPeopleNum;

        public string RoomPhotoUrl;

        public string Summary;

        public int RoomNum;
    }

}
