// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace HanTing
{

    public class Room
    {

        public string RoomTypeID;

        public string RoomTypeName;

        public string MarketPrice;

        public Info2 Info;

        public int ExchangePoint;

        public int PointExchangeRoomStatus;

        public Detail[] Details;

        public Cheapest Cheapest;
    }

}
